### ISSUE TITLE
duplicated packet in wireshark

### ISSUE THREAD

**Issue by vvzvlad** [g-oikonomou/sensniff#10]
I have run a sniffer on the instructions and accept packets in wireshark. I had a one probelmy: each packet is repeated 10 to 25 times in wireshark interface. This is the same packages as they have the same sequence number. I'm sending a simple udp-packet once, and it will be repeated 8 times in wireshark interface. I enclose a pcap file.
This sniffer bug or feature  802.14.5? Can you tell me how you can remove duplicate packets?
![screen 2017-01-02 0 17 59](https://cloud.githubusercontent.com/assets/3315944/21583082/f3d06d26-d080-11e6-83d0-4662e74e70c1.png)
[010117.pcap.zip](https://github.com/g-oikonomou/sensniff/files/680184/010117.pcap.zip)

**Comment by g-oikonomou** [comment]
This is neither a sensniff feature nor a bug. You are most likely using ContikiMAC (or similar mechanism at layer 2), which transmits outgoing frames multiple times. Sensniff captures and displays them all. This is perfectly normal behaviour.

If you are using Contiki, switching to NullRDC will stop this phenomenon.

**Comment by vvzvlad** [comment]
Yes I understand. Repeat packages used to increase the probability of successful delivery, I understand you correctly?

**Comment by g-oikonomou** [comment]
Yes there are more details but that's the basic principle

**Comment by vvzvlad** [comment]
Where can I read more details?

P.S. You do not know how in the MAC OS, you can run a sniffer in real time through the pipe? I got to do it only for linux.

**Comment by g-oikonomou** [comment]
There are a few academic papers plus a tech report on ContikiMAC for more details.

Sensniff works perfectly on OS X, it's my main development environment so I use it all the time (not upgraded to Sierra yet though)
