### ISSUE TITLE
Unexpected error: <type 'exceptions.NameError'>

### ISSUE THREAD

**Issue by marcomilazzo** [g-oikonomou/sensniff#16]
hi
i get the following error:
Unexpected error: <type 'exceptions.NameError'>

I'm under windows 7 and phyton 2.7
it looks to me that it doesn' create the pipe
A problem of permissions?
i have no experiance with phyton !
Can you help me?
thank's
marco

**Comment by g-oikonomou** [comment]
Have a look at branch win-support if you are not already using it. Win support very experimental and has limitations, I never really meant for it to be supported until a contributor actually went and made it happen.

Also suggest you have a look at the respective notes here: https://github.com/g-oikonomou/sensniff/tree/win-support#windows-specifics
