### ISSUE TITLE
sensniff contiki-ng is not working

### ISSUE THREAD

**Issue by th3g3ntl3mann** [g-oikonomou/sensniff#20]
Hi, I tried to run the sensniff application on the cooja simulator on contiki 3.0 and it is working very good, however when i use the application on the contiki-ng i get no mote output nor radio messages from the sensniff mote. any recommendations on how to se the sensniff application on a z1 mote on cooja and analyze the output on wireshark for example? thanks

**Comment by g-oikonomou** [comment]
I think I can suspect why it worked with Contiki 3.0, but you do not need to run sensniff inside Cooja anyway. Cooja will give you the entire pcap for post analysis with wireshark. Go to tools->Radio messages. Select Analyzer -> 6LoWPAN Analyzer with PCAP. At the end of the simulation, find a pcap file with all traffic under `tools/cooja/build`
