### ISSUE TITLE
Reported problems with the CC2531 USB dongle

### ISSUE THREAD

**Issue by g-oikonomou** [g-oikonomou/sensniff#5]
As per [this email](http://thread.gmane.org/gmane.os.contiki.devel/24041) in the contiki-developers mailing list, there may be issues when using with the CC2531 USB dongle.

This needs investigated

**Comment by arurke** [comment]
I'll just add a note:
I just made a build of the sensniff for CC2531 USB dongle, used it for two days without problems. Only deviation from your guides was that I used SDCC revision 9105, because there was some compliation problems with 9092.

**Comment by g-oikonomou** [comment]
Thanks for the feedback!

**Comment by arurke** [comment]
I'll just add another note:
I tried my CC2531 USB dongle on a Ubuntu in Virtualbox (USB3.0 enabled), and I got the same error as Muhammet Kaya after a few hundred frames. Same dongle worked fine on native. I switched to CC2538 so I don't think I will dig any deeper.
