### ISSUE TITLE
Magic bytes different in host code and documentation

### ISSUE THREAD

**Issue by ranganathpdg** [g-oikonomou/sensniff#7]
The magic byte sequence in GitHub README documentation is different to that of the host Python script. 

Last byte 0x72('r') is documented as 0x52('R').

In README:
MAGIC: The following 4 bytes (hex): C1 1F FE 52 ('S'+'n' 1F FE 'r')
In host side Script:
self.__sensniff_magic = struct.pack('BBBB', 0xC1, 0x1F, 0xFE, 0x72)

**Comment by g-oikonomou** [comment]
I've pushed a few changes so this should no longer be relevant.

**Comment by ranganathpdg** [comment]
Confirmed. README now matches with code.
