### ISSUE TITLE
Just a question about CC2531 usb dongle on Instant Contiki

### ISSUE THREAD

**Issue by chuijh** [g-oikonomou/sensniff#8]
Sorry I don't mean to post it as an issue, but I do have difficulty with using the dongle and the sensniff on Instant Contiki. I am seeing this:

user@instant-contiki:~/Downloads$ sudo python sensniff.py -d /dev/ttyACM1  -D INFO
Started logging
Serial port /dev/ttyACM1 opened
FIFO /tmp/sensniff exists. Using it
Commands:
c: Print current RF Channel
n: Trigger new pcap header before the next frame
h,?: Print this message
[11,26]: Change RF channel
q: Quit
Error reading port: /dev/ttyACM1
The error was: ('device reports readiness to read but returned no data (device disconnected or multiple access on port?)',)
Shutting down
Frame Stats:
           Non-Frame: 0
           Not Piped: 0
               Piped: 0
            Captured: 0

Does anyone know what may be the issue?

**Comment by brycekellogg** [comment]
I had the same issue and was able to fix it with the following changes:

```diff

diff --git a/host/sensniff.py b/host/sensniff.py
index d903370..ccaba53 100644
--- a/host/sensniff.py
+++ b/host/sensniff.py
@@ -140,6 +140,9 @@ class SerialInputHandler(object):
         logger.info('Serial port %s opened' % (self.port.name))
 
     def read_frame(self):
+        if (self.port.inWaiting() < 5):
+            return ''
+
         try:
             # Read the magic + 1 more byte
             b = self.port.read(5)
@@ -160,8 +163,9 @@ class SerialInputHandler(object):
 
         if b[0:4] not in (self.__sensniff_magic, self.__sensniff_magic_legacy):
             # Peripheral UART output - print it
-            per_out = self.port.readline().rstrip()
-            logger.info("Peripheral: %s%s" % (b, per_out))
+            self.port.flushInput()
+            #per_out = self.port.readline().rstrip()
+            #logger.info("Peripheral: %s%s" % (b, per_out))
             stats['Non-Frame'] += 1
             return ''
 
@@ -172,6 +176,9 @@ class SerialInputHandler(object):
         if b[4] != SNIFFER_PROTO_VERSION:
             # Legacy contiki sniffer support. Will slowly fade away
             size = b[4]
+            if (self.port.inWaiting() < size):
+                return ''
+
             try:
                 b = self.port.read(size)
             except (IOError, OSError) as e:

```

**Comment by g-oikonomou** [comment]
Could it be that the dongle is connected to a USB 3 port? Are you getting the same behaviour if you connect it to all ports on your host? I have _never_ seen this myself, but where there is smoke...
